<?php

namespace SCM\ProcessBundle\Repository;

/**
 * ProcessFlowRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProcessFlowRepository extends \Doctrine\ORM\EntityRepository
{
}
